### ISSUE TITLE
About XDMCP on RPi

### ISSUE THREAD

**Issue by MikePryadko** [micwan88/micwan88.github.io#1]
If you use `ssh -X` so for what do you configure lightdm to listen tcp?? it's two different things!

**Comment by micwan88** [comment]
@MikePryadko It is mentioned that in `Pre-requisite` section, we have to modify `/etc/lightdm/lightdm.conf` by setting `xserver-allow-tcp=true` to enable lightdm to have listen TCP connection.
Does it work for you ?
